<?php

return [
    'paddle_webhook_secret' => env('PADDLE_WEBHOOK_SECRET'),
    'paddle_customer_token' => env('PADDLE_CUSTOMER_TOKEN'),
    'sandbox' => env('PADDLE_SANDBOX'),
    'api_key' => env('PADDLE_API_KEY'),
    'grace_days' => (int) env('BILLING_GRACE_DAYS', 7),

    'plans' => [
        'free' => [
            'name' => 'Free',
            'price_monthly' => 0,
            'price_yearly' => 0,
            'price_ids' => [],
            'monitors' => 3,
            'users' => 1,
            'check_interval' => '15-minute',
            'history_days' => 1,
            'popular' => false,
            'description' => 'For trying Monitly with a single account.',
            'feature_list' => [
                '3 monitors',
                '15-minute checks',
                '1 user only',
                '24 hour history',
                'Email notifications only',
                'No SLA',
            ],
            'audience' => 'normal',
        ],
        'pro' => [
            'name' => 'Pro',
            'price_monthly' => 9,
            'price_yearly' => 90,
            'price_ids' => [
                'monthly' => env('PADDLE_PRICE_ID_PRO_MONTHLY'),
                'yearly' => env('PADDLE_PRICE_ID_PRO_YEARLY'),
            ],
            'monitors' => 15,
            'users' => 1,
            'check_interval' => '10-minute',
            'history_days' => 30,
            'popular' => true,
            'description' => 'For serious solo monitoring.',
            'feature_list' => [
                '15 monitors',
                '10-minute checks',
                '1 user only',
                '30 days history',
                'SLA + PDF',
            ],
            'audience' => 'normal',
        ],
        'team' => [
            'name' => 'Team',
            'price_monthly' => 29,
            'price_yearly' => 290,
            'price_ids' => [
                'monthly' => env('PADDLE_PRICE_ID_TEAM_MONTHLY'),
                'yearly' => env('PADDLE_PRICE_ID_TEAM_YEARLY'),
            ],
            'monitors' => 50,
            'users' => 5,
            'check_interval' => '10-minute',
            'history_days' => 90,
            'popular' => false,
            'best_value' => true,
            'description' => 'For teams that need shared monitoring.',
            'feature_list' => [
                '50 monitors',
                '10-minute checks',
                'Up to 5 users',
                '90 days history',
                'SLA + PDF',
            ],
            'audience' => 'team',
        ],
        'business' => [
            'name' => 'Business',
            'price_monthly' => 79,
            'price_yearly' => 790,
            'price_ids' => [
                'monthly' => env('PADDLE_PRICE_ID_BUSINESS_MONTHLY'),
                'yearly' => env('PADDLE_PRICE_ID_BUSINESS_YEARLY'),
            ],
            'monitors' => 150,
            'users' => 15,
            'check_interval' => '5-minute',
            'history_days' => 365,
            'popular' => false,
            'description' => 'For critical uptime and priority queue.',
            'feature_list' => [
                '150 monitors',
                '5-minute checks',
                'Up to 15 users',
                '365 days history',
                'SLA + PDF',
                'Priority queue',
            ],
            'audience' => 'team',
        ],
    ],

    'addons' => [],
];
